# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.10.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Condition(BaseModel):
    """
    Condition
    """ # noqa: E501
    execution_config_sha256: Annotated[str, Field(strict=True)]
    bank_id: Annotated[str, Field(min_length=1, strict=True, max_length=256)]
    source_id: Annotated[str, Field(min_length=1, strict=True, max_length=1024)]
    source_sha256: Annotated[str, Field(strict=True)]
    source_updated_at: StrictStr
    source_metadata_sha256: Annotated[str, Field(strict=True)]
    target_id: Annotated[str, Field(min_length=1, strict=True, max_length=1024)]
    target_sha256: Annotated[str, Field(strict=True)]
    owner_key: Annotated[str, Field(min_length=32, strict=True, max_length=128)]
    operation_id: StrictStr
    payload_sha256: Annotated[str, Field(strict=True)]
    __properties: ClassVar[List[str]] = ["execution_config_sha256", "bank_id", "source_id", "source_sha256", "source_updated_at", "source_metadata_sha256", "target_id", "target_sha256", "owner_key", "operation_id", "payload_sha256"]

    @field_validator('execution_config_sha256')
    def execution_config_sha256_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[a-f0-9]{64}$/")
        return value

    @field_validator('source_sha256')
    def source_sha256_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[a-f0-9]{64}$/")
        return value

    @field_validator('source_metadata_sha256')
    def source_metadata_sha256_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[a-f0-9]{64}$/")
        return value

    @field_validator('target_sha256')
    def target_sha256_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[a-f0-9]{64}$/")
        return value

    @field_validator('payload_sha256')
    def payload_sha256_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-f0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[a-f0-9]{64}$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Condition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Condition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "execution_config_sha256": obj.get("execution_config_sha256"),
            "bank_id": obj.get("bank_id"),
            "source_id": obj.get("source_id"),
            "source_sha256": obj.get("source_sha256"),
            "source_updated_at": obj.get("source_updated_at"),
            "source_metadata_sha256": obj.get("source_metadata_sha256"),
            "target_id": obj.get("target_id"),
            "target_sha256": obj.get("target_sha256"),
            "owner_key": obj.get("owner_key"),
            "operation_id": obj.get("operation_id"),
            "payload_sha256": obj.get("payload_sha256")
        })
        return _obj
