# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.10.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Receipt(BaseModel):
    """
    Receipt
    """ # noqa: E501
    condition_sha256: StrictStr
    operation_id: StrictStr
    payload_sha256: StrictStr
    target_id: StrictStr
    owner_key: StrictStr
    target_sha256: StrictStr
    metadata_sha256: StrictStr
    graph_sha256: StrictStr
    updated_at: StrictStr
    status: Optional[StrictStr] = 'completed'
    created: Optional[StrictBool] = True
    rollback_operation_id: Optional[StrictStr]
    rollback_payload_sha256: Optional[StrictStr]
    created_receipt_sha256: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["condition_sha256", "operation_id", "payload_sha256", "target_id", "owner_key", "target_sha256", "metadata_sha256", "graph_sha256", "updated_at", "status", "created", "rollback_operation_id", "rollback_payload_sha256", "created_receipt_sha256"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['completed', 'rolled_back']):
            raise ValueError("must be one of enum values ('completed', 'rolled_back')")
        return value

    @field_validator('created')
    def created_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([True]):
            raise ValueError("must be one of enum values (True)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Receipt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if rollback_operation_id (nullable) is None
        # and model_fields_set contains the field
        if self.rollback_operation_id is None and "rollback_operation_id" in self.model_fields_set:
            _dict['rollback_operation_id'] = None

        # set to None if rollback_payload_sha256 (nullable) is None
        # and model_fields_set contains the field
        if self.rollback_payload_sha256 is None and "rollback_payload_sha256" in self.model_fields_set:
            _dict['rollback_payload_sha256'] = None

        # set to None if created_receipt_sha256 (nullable) is None
        # and model_fields_set contains the field
        if self.created_receipt_sha256 is None and "created_receipt_sha256" in self.model_fields_set:
            _dict['created_receipt_sha256'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Receipt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "condition_sha256": obj.get("condition_sha256"),
            "operation_id": obj.get("operation_id"),
            "payload_sha256": obj.get("payload_sha256"),
            "target_id": obj.get("target_id"),
            "owner_key": obj.get("owner_key"),
            "target_sha256": obj.get("target_sha256"),
            "metadata_sha256": obj.get("metadata_sha256"),
            "graph_sha256": obj.get("graph_sha256"),
            "updated_at": obj.get("updated_at"),
            "status": obj.get("status") if obj.get("status") is not None else 'completed',
            "created": obj.get("created") if obj.get("created") is not None else True,
            "rollback_operation_id": obj.get("rollback_operation_id"),
            "rollback_payload_sha256": obj.get("rollback_payload_sha256"),
            "created_receipt_sha256": obj.get("created_receipt_sha256")
        })
        return _obj
