/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RollbackRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RollbackRequest{}

// RollbackRequest struct for RollbackRequest
type RollbackRequest struct {
	Condition Condition `json:"condition"`
	ExpectedUpdatedAt string `json:"expected_updated_at"`
	RollbackOperationId string `json:"rollback_operation_id"`
	RollbackPayloadSha256 string `json:"rollback_payload_sha256" validate:"regexp=^[a-f0-9]{64}$"`
	CreatedReceiptSha256 string `json:"created_receipt_sha256" validate:"regexp=^[a-f0-9]{64}$"`
	ExpectedDocumentMetadataSha256 string `json:"expected_document_metadata_sha256" validate:"regexp=^[a-f0-9]{64}$"`
}

type _RollbackRequest RollbackRequest

// NewRollbackRequest instantiates a new RollbackRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRollbackRequest(condition Condition, expectedUpdatedAt string, rollbackOperationId string, rollbackPayloadSha256 string, createdReceiptSha256 string, expectedDocumentMetadataSha256 string) *RollbackRequest {
	this := RollbackRequest{}
	this.Condition = condition
	this.ExpectedUpdatedAt = expectedUpdatedAt
	this.RollbackOperationId = rollbackOperationId
	this.RollbackPayloadSha256 = rollbackPayloadSha256
	this.CreatedReceiptSha256 = createdReceiptSha256
	this.ExpectedDocumentMetadataSha256 = expectedDocumentMetadataSha256
	return &this
}

// NewRollbackRequestWithDefaults instantiates a new RollbackRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRollbackRequestWithDefaults() *RollbackRequest {
	this := RollbackRequest{}
	return &this
}

// GetCondition returns the Condition field value
func (o *RollbackRequest) GetCondition() Condition {
	if o == nil {
		var ret Condition
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *RollbackRequest) GetConditionOk() (*Condition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *RollbackRequest) SetCondition(v Condition) {
	o.Condition = v
}

// GetExpectedUpdatedAt returns the ExpectedUpdatedAt field value
func (o *RollbackRequest) GetExpectedUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedUpdatedAt
}

// GetExpectedUpdatedAtOk returns a tuple with the ExpectedUpdatedAt field value
// and a boolean to check if the value has been set.
func (o *RollbackRequest) GetExpectedUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedUpdatedAt, true
}

// SetExpectedUpdatedAt sets field value
func (o *RollbackRequest) SetExpectedUpdatedAt(v string) {
	o.ExpectedUpdatedAt = v
}

// GetRollbackOperationId returns the RollbackOperationId field value
func (o *RollbackRequest) GetRollbackOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RollbackOperationId
}

// GetRollbackOperationIdOk returns a tuple with the RollbackOperationId field value
// and a boolean to check if the value has been set.
func (o *RollbackRequest) GetRollbackOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RollbackOperationId, true
}

// SetRollbackOperationId sets field value
func (o *RollbackRequest) SetRollbackOperationId(v string) {
	o.RollbackOperationId = v
}

// GetRollbackPayloadSha256 returns the RollbackPayloadSha256 field value
func (o *RollbackRequest) GetRollbackPayloadSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RollbackPayloadSha256
}

// GetRollbackPayloadSha256Ok returns a tuple with the RollbackPayloadSha256 field value
// and a boolean to check if the value has been set.
func (o *RollbackRequest) GetRollbackPayloadSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RollbackPayloadSha256, true
}

// SetRollbackPayloadSha256 sets field value
func (o *RollbackRequest) SetRollbackPayloadSha256(v string) {
	o.RollbackPayloadSha256 = v
}

// GetCreatedReceiptSha256 returns the CreatedReceiptSha256 field value
func (o *RollbackRequest) GetCreatedReceiptSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedReceiptSha256
}

// GetCreatedReceiptSha256Ok returns a tuple with the CreatedReceiptSha256 field value
// and a boolean to check if the value has been set.
func (o *RollbackRequest) GetCreatedReceiptSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedReceiptSha256, true
}

// SetCreatedReceiptSha256 sets field value
func (o *RollbackRequest) SetCreatedReceiptSha256(v string) {
	o.CreatedReceiptSha256 = v
}

// GetExpectedDocumentMetadataSha256 returns the ExpectedDocumentMetadataSha256 field value
func (o *RollbackRequest) GetExpectedDocumentMetadataSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedDocumentMetadataSha256
}

// GetExpectedDocumentMetadataSha256Ok returns a tuple with the ExpectedDocumentMetadataSha256 field value
// and a boolean to check if the value has been set.
func (o *RollbackRequest) GetExpectedDocumentMetadataSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedDocumentMetadataSha256, true
}

// SetExpectedDocumentMetadataSha256 sets field value
func (o *RollbackRequest) SetExpectedDocumentMetadataSha256(v string) {
	o.ExpectedDocumentMetadataSha256 = v
}

func (o RollbackRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RollbackRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["condition"] = o.Condition
	toSerialize["expected_updated_at"] = o.ExpectedUpdatedAt
	toSerialize["rollback_operation_id"] = o.RollbackOperationId
	toSerialize["rollback_payload_sha256"] = o.RollbackPayloadSha256
	toSerialize["created_receipt_sha256"] = o.CreatedReceiptSha256
	toSerialize["expected_document_metadata_sha256"] = o.ExpectedDocumentMetadataSha256
	return toSerialize, nil
}

func (o *RollbackRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"condition",
		"expected_updated_at",
		"rollback_operation_id",
		"rollback_payload_sha256",
		"created_receipt_sha256",
		"expected_document_metadata_sha256",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRollbackRequest := _RollbackRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRollbackRequest)

	if err != nil {
		return err
	}

	*o = RollbackRequest(varRollbackRequest)

	return err
}

type NullableRollbackRequest struct {
	value *RollbackRequest
	isSet bool
}

func (v NullableRollbackRequest) Get() *RollbackRequest {
	return v.value
}

func (v *NullableRollbackRequest) Set(val *RollbackRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRollbackRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRollbackRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRollbackRequest(val *RollbackRequest) *NullableRollbackRequest {
	return &NullableRollbackRequest{value: val, isSet: true}
}

func (v NullableRollbackRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRollbackRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
