/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Condition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Condition{}

// Condition struct for Condition
type Condition struct {
	ExecutionConfigSha256 string `json:"execution_config_sha256" validate:"regexp=^[a-f0-9]{64}$"`
	BankId string `json:"bank_id"`
	SourceId string `json:"source_id"`
	SourceSha256 string `json:"source_sha256" validate:"regexp=^[a-f0-9]{64}$"`
	SourceUpdatedAt string `json:"source_updated_at"`
	SourceMetadataSha256 string `json:"source_metadata_sha256" validate:"regexp=^[a-f0-9]{64}$"`
	TargetId string `json:"target_id"`
	TargetSha256 string `json:"target_sha256" validate:"regexp=^[a-f0-9]{64}$"`
	OwnerKey string `json:"owner_key"`
	OperationId string `json:"operation_id"`
	PayloadSha256 string `json:"payload_sha256" validate:"regexp=^[a-f0-9]{64}$"`
}

type _Condition Condition

// NewCondition instantiates a new Condition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCondition(executionConfigSha256 string, bankId string, sourceId string, sourceSha256 string, sourceUpdatedAt string, sourceMetadataSha256 string, targetId string, targetSha256 string, ownerKey string, operationId string, payloadSha256 string) *Condition {
	this := Condition{}
	this.ExecutionConfigSha256 = executionConfigSha256
	this.BankId = bankId
	this.SourceId = sourceId
	this.SourceSha256 = sourceSha256
	this.SourceUpdatedAt = sourceUpdatedAt
	this.SourceMetadataSha256 = sourceMetadataSha256
	this.TargetId = targetId
	this.TargetSha256 = targetSha256
	this.OwnerKey = ownerKey
	this.OperationId = operationId
	this.PayloadSha256 = payloadSha256
	return &this
}

// NewConditionWithDefaults instantiates a new Condition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConditionWithDefaults() *Condition {
	this := Condition{}
	return &this
}

// GetExecutionConfigSha256 returns the ExecutionConfigSha256 field value
func (o *Condition) GetExecutionConfigSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExecutionConfigSha256
}

// GetExecutionConfigSha256Ok returns a tuple with the ExecutionConfigSha256 field value
// and a boolean to check if the value has been set.
func (o *Condition) GetExecutionConfigSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExecutionConfigSha256, true
}

// SetExecutionConfigSha256 sets field value
func (o *Condition) SetExecutionConfigSha256(v string) {
	o.ExecutionConfigSha256 = v
}

// GetBankId returns the BankId field value
func (o *Condition) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *Condition) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *Condition) SetBankId(v string) {
	o.BankId = v
}

// GetSourceId returns the SourceId field value
func (o *Condition) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *Condition) GetSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *Condition) SetSourceId(v string) {
	o.SourceId = v
}

// GetSourceSha256 returns the SourceSha256 field value
func (o *Condition) GetSourceSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceSha256
}

// GetSourceSha256Ok returns a tuple with the SourceSha256 field value
// and a boolean to check if the value has been set.
func (o *Condition) GetSourceSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceSha256, true
}

// SetSourceSha256 sets field value
func (o *Condition) SetSourceSha256(v string) {
	o.SourceSha256 = v
}

// GetSourceUpdatedAt returns the SourceUpdatedAt field value
func (o *Condition) GetSourceUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceUpdatedAt
}

// GetSourceUpdatedAtOk returns a tuple with the SourceUpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Condition) GetSourceUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceUpdatedAt, true
}

// SetSourceUpdatedAt sets field value
func (o *Condition) SetSourceUpdatedAt(v string) {
	o.SourceUpdatedAt = v
}

// GetSourceMetadataSha256 returns the SourceMetadataSha256 field value
func (o *Condition) GetSourceMetadataSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceMetadataSha256
}

// GetSourceMetadataSha256Ok returns a tuple with the SourceMetadataSha256 field value
// and a boolean to check if the value has been set.
func (o *Condition) GetSourceMetadataSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceMetadataSha256, true
}

// SetSourceMetadataSha256 sets field value
func (o *Condition) SetSourceMetadataSha256(v string) {
	o.SourceMetadataSha256 = v
}

// GetTargetId returns the TargetId field value
func (o *Condition) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *Condition) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *Condition) SetTargetId(v string) {
	o.TargetId = v
}

// GetTargetSha256 returns the TargetSha256 field value
func (o *Condition) GetTargetSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetSha256
}

// GetTargetSha256Ok returns a tuple with the TargetSha256 field value
// and a boolean to check if the value has been set.
func (o *Condition) GetTargetSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetSha256, true
}

// SetTargetSha256 sets field value
func (o *Condition) SetTargetSha256(v string) {
	o.TargetSha256 = v
}

// GetOwnerKey returns the OwnerKey field value
func (o *Condition) GetOwnerKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerKey
}

// GetOwnerKeyOk returns a tuple with the OwnerKey field value
// and a boolean to check if the value has been set.
func (o *Condition) GetOwnerKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerKey, true
}

// SetOwnerKey sets field value
func (o *Condition) SetOwnerKey(v string) {
	o.OwnerKey = v
}

// GetOperationId returns the OperationId field value
func (o *Condition) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *Condition) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *Condition) SetOperationId(v string) {
	o.OperationId = v
}

// GetPayloadSha256 returns the PayloadSha256 field value
func (o *Condition) GetPayloadSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PayloadSha256
}

// GetPayloadSha256Ok returns a tuple with the PayloadSha256 field value
// and a boolean to check if the value has been set.
func (o *Condition) GetPayloadSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PayloadSha256, true
}

// SetPayloadSha256 sets field value
func (o *Condition) SetPayloadSha256(v string) {
	o.PayloadSha256 = v
}

func (o Condition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Condition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["execution_config_sha256"] = o.ExecutionConfigSha256
	toSerialize["bank_id"] = o.BankId
	toSerialize["source_id"] = o.SourceId
	toSerialize["source_sha256"] = o.SourceSha256
	toSerialize["source_updated_at"] = o.SourceUpdatedAt
	toSerialize["source_metadata_sha256"] = o.SourceMetadataSha256
	toSerialize["target_id"] = o.TargetId
	toSerialize["target_sha256"] = o.TargetSha256
	toSerialize["owner_key"] = o.OwnerKey
	toSerialize["operation_id"] = o.OperationId
	toSerialize["payload_sha256"] = o.PayloadSha256
	return toSerialize, nil
}

func (o *Condition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"execution_config_sha256",
		"bank_id",
		"source_id",
		"source_sha256",
		"source_updated_at",
		"source_metadata_sha256",
		"target_id",
		"target_sha256",
		"owner_key",
		"operation_id",
		"payload_sha256",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCondition := _Condition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCondition)

	if err != nil {
		return err
	}

	*o = Condition(varCondition)

	return err
}

type NullableCondition struct {
	value *Condition
	isSet bool
}

func (v NullableCondition) Get() *Condition {
	return v.value
}

func (v *NullableCondition) Set(val *Condition) {
	v.value = val
	v.isSet = true
}

func (v NullableCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCondition(val *Condition) *NullableCondition {
	return &NullableCondition{value: val, isSet: true}
}

func (v NullableCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
