/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Capabilities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Capabilities{}

// Capabilities struct for Capabilities
type Capabilities struct {
	AtomicCreate bool `json:"atomic_create"`
	AtomicSourceCheck bool `json:"atomic_source_check"`
	ConditionalDelete bool `json:"conditional_delete"`
	ContractId *string `json:"contract_id,omitempty"`
	Reason NullableString `json:"reason,omitempty"`
}

type _Capabilities Capabilities

// NewCapabilities instantiates a new Capabilities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCapabilities(atomicCreate bool, atomicSourceCheck bool, conditionalDelete bool) *Capabilities {
	this := Capabilities{}
	this.AtomicCreate = atomicCreate
	this.AtomicSourceCheck = atomicSourceCheck
	this.ConditionalDelete = conditionalDelete
	var contractId string = "cleaner-atomic-v1"
	this.ContractId = &contractId
	return &this
}

// NewCapabilitiesWithDefaults instantiates a new Capabilities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCapabilitiesWithDefaults() *Capabilities {
	this := Capabilities{}
	var contractId string = "cleaner-atomic-v1"
	this.ContractId = &contractId
	return &this
}

// GetAtomicCreate returns the AtomicCreate field value
func (o *Capabilities) GetAtomicCreate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AtomicCreate
}

// GetAtomicCreateOk returns a tuple with the AtomicCreate field value
// and a boolean to check if the value has been set.
func (o *Capabilities) GetAtomicCreateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AtomicCreate, true
}

// SetAtomicCreate sets field value
func (o *Capabilities) SetAtomicCreate(v bool) {
	o.AtomicCreate = v
}

// GetAtomicSourceCheck returns the AtomicSourceCheck field value
func (o *Capabilities) GetAtomicSourceCheck() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AtomicSourceCheck
}

// GetAtomicSourceCheckOk returns a tuple with the AtomicSourceCheck field value
// and a boolean to check if the value has been set.
func (o *Capabilities) GetAtomicSourceCheckOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AtomicSourceCheck, true
}

// SetAtomicSourceCheck sets field value
func (o *Capabilities) SetAtomicSourceCheck(v bool) {
	o.AtomicSourceCheck = v
}

// GetConditionalDelete returns the ConditionalDelete field value
func (o *Capabilities) GetConditionalDelete() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ConditionalDelete
}

// GetConditionalDeleteOk returns a tuple with the ConditionalDelete field value
// and a boolean to check if the value has been set.
func (o *Capabilities) GetConditionalDeleteOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionalDelete, true
}

// SetConditionalDelete sets field value
func (o *Capabilities) SetConditionalDelete(v bool) {
	o.ConditionalDelete = v
}

// GetContractId returns the ContractId field value if set, zero value otherwise.
func (o *Capabilities) GetContractId() string {
	if o == nil || IsNil(o.ContractId) {
		var ret string
		return ret
	}
	return *o.ContractId
}

// GetContractIdOk returns a tuple with the ContractId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Capabilities) GetContractIdOk() (*string, bool) {
	if o == nil || IsNil(o.ContractId) {
		return nil, false
	}
	return o.ContractId, true
}

// HasContractId returns a boolean if a field has been set.
func (o *Capabilities) HasContractId() bool {
	if o != nil && !IsNil(o.ContractId) {
		return true
	}

	return false
}

// SetContractId gets a reference to the given string and assigns it to the ContractId field.
func (o *Capabilities) SetContractId(v string) {
	o.ContractId = &v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Capabilities) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Capabilities) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *Capabilities) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *Capabilities) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *Capabilities) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *Capabilities) UnsetReason() {
	o.Reason.Unset()
}

func (o Capabilities) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Capabilities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["atomic_create"] = o.AtomicCreate
	toSerialize["atomic_source_check"] = o.AtomicSourceCheck
	toSerialize["conditional_delete"] = o.ConditionalDelete
	if !IsNil(o.ContractId) {
		toSerialize["contract_id"] = o.ContractId
	}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	return toSerialize, nil
}

func (o *Capabilities) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"atomic_create",
		"atomic_source_check",
		"conditional_delete",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCapabilities := _Capabilities{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCapabilities)

	if err != nil {
		return err
	}

	*o = Capabilities(varCapabilities)

	return err
}

type NullableCapabilities struct {
	value *Capabilities
	isSet bool
}

func (v NullableCapabilities) Get() *Capabilities {
	return v.value
}

func (v *NullableCapabilities) Set(val *Capabilities) {
	v.value = val
	v.isSet = true
}

func (v NullableCapabilities) IsSet() bool {
	return v.isSet
}

func (v *NullableCapabilities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCapabilities(val *Capabilities) *NullableCapabilities {
	return &NullableCapabilities{value: val, isSet: true}
}

func (v NullableCapabilities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCapabilities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
