/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Receipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Receipt{}

// Receipt struct for Receipt
type Receipt struct {
	ConditionSha256 string `json:"condition_sha256"`
	OperationId string `json:"operation_id"`
	PayloadSha256 string `json:"payload_sha256"`
	TargetId string `json:"target_id"`
	OwnerKey string `json:"owner_key"`
	TargetSha256 string `json:"target_sha256"`
	MetadataSha256 string `json:"metadata_sha256"`
	GraphSha256 string `json:"graph_sha256"`
	UpdatedAt string `json:"updated_at"`
	Status *string `json:"status,omitempty"`
	Created *bool `json:"created,omitempty"`
	RollbackOperationId NullableString `json:"rollback_operation_id"`
	RollbackPayloadSha256 NullableString `json:"rollback_payload_sha256"`
	CreatedReceiptSha256 NullableString `json:"created_receipt_sha256"`
}

type _Receipt Receipt

// NewReceipt instantiates a new Receipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceipt(conditionSha256 string, operationId string, payloadSha256 string, targetId string, ownerKey string, targetSha256 string, metadataSha256 string, graphSha256 string, updatedAt string, rollbackOperationId NullableString, rollbackPayloadSha256 NullableString, createdReceiptSha256 NullableString) *Receipt {
	this := Receipt{}
	this.ConditionSha256 = conditionSha256
	this.OperationId = operationId
	this.PayloadSha256 = payloadSha256
	this.TargetId = targetId
	this.OwnerKey = ownerKey
	this.TargetSha256 = targetSha256
	this.MetadataSha256 = metadataSha256
	this.GraphSha256 = graphSha256
	this.UpdatedAt = updatedAt
	var status string = "completed"
	this.Status = &status
	var created bool = true
	this.Created = &created
	this.RollbackOperationId = rollbackOperationId
	this.RollbackPayloadSha256 = rollbackPayloadSha256
	this.CreatedReceiptSha256 = createdReceiptSha256
	return &this
}

// NewReceiptWithDefaults instantiates a new Receipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptWithDefaults() *Receipt {
	this := Receipt{}
	var status string = "completed"
	this.Status = &status
	var created bool = true
	this.Created = &created
	return &this
}

// GetConditionSha256 returns the ConditionSha256 field value
func (o *Receipt) GetConditionSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConditionSha256
}

// GetConditionSha256Ok returns a tuple with the ConditionSha256 field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetConditionSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConditionSha256, true
}

// SetConditionSha256 sets field value
func (o *Receipt) SetConditionSha256(v string) {
	o.ConditionSha256 = v
}

// GetOperationId returns the OperationId field value
func (o *Receipt) GetOperationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OperationId, true
}

// SetOperationId sets field value
func (o *Receipt) SetOperationId(v string) {
	o.OperationId = v
}

// GetPayloadSha256 returns the PayloadSha256 field value
func (o *Receipt) GetPayloadSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PayloadSha256
}

// GetPayloadSha256Ok returns a tuple with the PayloadSha256 field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetPayloadSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PayloadSha256, true
}

// SetPayloadSha256 sets field value
func (o *Receipt) SetPayloadSha256(v string) {
	o.PayloadSha256 = v
}

// GetTargetId returns the TargetId field value
func (o *Receipt) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *Receipt) SetTargetId(v string) {
	o.TargetId = v
}

// GetOwnerKey returns the OwnerKey field value
func (o *Receipt) GetOwnerKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OwnerKey
}

// GetOwnerKeyOk returns a tuple with the OwnerKey field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetOwnerKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OwnerKey, true
}

// SetOwnerKey sets field value
func (o *Receipt) SetOwnerKey(v string) {
	o.OwnerKey = v
}

// GetTargetSha256 returns the TargetSha256 field value
func (o *Receipt) GetTargetSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetSha256
}

// GetTargetSha256Ok returns a tuple with the TargetSha256 field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetTargetSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetSha256, true
}

// SetTargetSha256 sets field value
func (o *Receipt) SetTargetSha256(v string) {
	o.TargetSha256 = v
}

// GetMetadataSha256 returns the MetadataSha256 field value
func (o *Receipt) GetMetadataSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetadataSha256
}

// GetMetadataSha256Ok returns a tuple with the MetadataSha256 field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetMetadataSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetadataSha256, true
}

// SetMetadataSha256 sets field value
func (o *Receipt) SetMetadataSha256(v string) {
	o.MetadataSha256 = v
}

// GetGraphSha256 returns the GraphSha256 field value
func (o *Receipt) GetGraphSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GraphSha256
}

// GetGraphSha256Ok returns a tuple with the GraphSha256 field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetGraphSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GraphSha256, true
}

// SetGraphSha256 sets field value
func (o *Receipt) SetGraphSha256(v string) {
	o.GraphSha256 = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Receipt) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Receipt) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Receipt) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Receipt) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Receipt) SetStatus(v string) {
	o.Status = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Receipt) GetCreated() bool {
	if o == nil || IsNil(o.Created) {
		var ret bool
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetCreatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Receipt) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given bool and assigns it to the Created field.
func (o *Receipt) SetCreated(v bool) {
	o.Created = &v
}

// GetRollbackOperationId returns the RollbackOperationId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Receipt) GetRollbackOperationId() string {
	if o == nil || o.RollbackOperationId.Get() == nil {
		var ret string
		return ret
	}

	return *o.RollbackOperationId.Get()
}

// GetRollbackOperationIdOk returns a tuple with the RollbackOperationId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Receipt) GetRollbackOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RollbackOperationId.Get(), o.RollbackOperationId.IsSet()
}

// SetRollbackOperationId sets field value
func (o *Receipt) SetRollbackOperationId(v string) {
	o.RollbackOperationId.Set(&v)
}

// GetRollbackPayloadSha256 returns the RollbackPayloadSha256 field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Receipt) GetRollbackPayloadSha256() string {
	if o == nil || o.RollbackPayloadSha256.Get() == nil {
		var ret string
		return ret
	}

	return *o.RollbackPayloadSha256.Get()
}

// GetRollbackPayloadSha256Ok returns a tuple with the RollbackPayloadSha256 field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Receipt) GetRollbackPayloadSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RollbackPayloadSha256.Get(), o.RollbackPayloadSha256.IsSet()
}

// SetRollbackPayloadSha256 sets field value
func (o *Receipt) SetRollbackPayloadSha256(v string) {
	o.RollbackPayloadSha256.Set(&v)
}

// GetCreatedReceiptSha256 returns the CreatedReceiptSha256 field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Receipt) GetCreatedReceiptSha256() string {
	if o == nil || o.CreatedReceiptSha256.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreatedReceiptSha256.Get()
}

// GetCreatedReceiptSha256Ok returns a tuple with the CreatedReceiptSha256 field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Receipt) GetCreatedReceiptSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedReceiptSha256.Get(), o.CreatedReceiptSha256.IsSet()
}

// SetCreatedReceiptSha256 sets field value
func (o *Receipt) SetCreatedReceiptSha256(v string) {
	o.CreatedReceiptSha256.Set(&v)
}

func (o Receipt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Receipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["condition_sha256"] = o.ConditionSha256
	toSerialize["operation_id"] = o.OperationId
	toSerialize["payload_sha256"] = o.PayloadSha256
	toSerialize["target_id"] = o.TargetId
	toSerialize["owner_key"] = o.OwnerKey
	toSerialize["target_sha256"] = o.TargetSha256
	toSerialize["metadata_sha256"] = o.MetadataSha256
	toSerialize["graph_sha256"] = o.GraphSha256
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	toSerialize["rollback_operation_id"] = o.RollbackOperationId.Get()
	toSerialize["rollback_payload_sha256"] = o.RollbackPayloadSha256.Get()
	toSerialize["created_receipt_sha256"] = o.CreatedReceiptSha256.Get()
	return toSerialize, nil
}

func (o *Receipt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"condition_sha256",
		"operation_id",
		"payload_sha256",
		"target_id",
		"owner_key",
		"target_sha256",
		"metadata_sha256",
		"graph_sha256",
		"updated_at",
		"rollback_operation_id",
		"rollback_payload_sha256",
		"created_receipt_sha256",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceipt := _Receipt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReceipt)

	if err != nil {
		return err
	}

	*o = Receipt(varReceipt)

	return err
}

type NullableReceipt struct {
	value *Receipt
	isSet bool
}

func (v NullableReceipt) Get() *Receipt {
	return v.value
}

func (v *NullableReceipt) Set(val *Receipt) {
	v.value = val
	v.isSet = true
}

func (v NullableReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullableReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceipt(val *Receipt) *NullableReceipt {
	return &NullableReceipt{value: val, isSet: true}
}

func (v NullableReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
